# Generated by Django 3.2.7 on 2021-09-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_attendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='an',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='fn',
        ),
    ]
